export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_STORIES_PENDING = 'REQUEST_STORIES_PENDING';
export const REQUEST_STORIES_SUCCESS = 'REQUEST_STORIES_SUCCESS';
export const REQUEST_STORIES_FAILED = 'REQUEST_STORIES_FAILED';
